version: '3'

services:
  crawl_worker:
    image: tschachn/crawl_worker:latest
    ports:
      - "3333:3333"
    deploy:
      replicas: 10
      placement:
        constraints: [node.labels.type == crawl_worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1500M
        reservations:
          cpus: '.75'
          memory: 1000M